name: housekeeper
description: A housekeeping tool facilitating automation and CI needs around sum_types project.
version: 0.1.0
homepage: https://github.com/werediver/sum-types-dart
author: Raman Fedaseyeu <raman.fedaseyeu@gmail.com>
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta:
  path:

dev_dependencies:
  dependency_validator:

executables:
  housekeeper:
